
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 21 19:20:15 PDT 2023
//----------------------------------------------------

package Code;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int tk_asignacion_resta = 53;
  public static final int tk_logico = 18;
  public static final int tk_para = 37;
  public static final int tk_fecha_real = 8;
  public static final int tk_rfc = 23;
  public static final int tk_o = 64;
  public static final int tk_decimal = 15;
  public static final int tk_variable = 13;
  public static final int tk_romper = 38;
  public static final int tk_incremento = 49;
  public static final int tk_hora = 21;
  public static final int tk_texto = 17;
  public static final int tk_curp = 22;
  public static final int tk_asignacion_modulo = 56;
  public static final int tk_decremento = 50;
  public static final int tk_division = 47;
  public static final int Error = 67;
  public static final int tk_variables = 12;
  public static final int tk_mayor_igual = 61;
  public static final int tk_inicio = 31;
  public static final int tk_parentesis_abierto = 39;
  public static final int tk_fecha_hora = 19;
  public static final int tk_fin = 32;
  public static final int tk_simbolo_real = 5;
  public static final int tk_asignacion = 51;
  public static final int tk_identificador = 66;
  public static final int tk_resta = 45;
  public static final int tk_menor_igual = 62;
  public static final int tk_asignacion_suma = 52;
  public static final int tk_devolver = 29;
  public static final int tk_fecha = 20;
  public static final int EOF = 0;
  public static final int tk_procedimiento = 28;
  public static final int tk_sino = 35;
  public static final int error = 1;
  public static final int tk_si = 33;
  public static final int tk_entonces = 34;
  public static final int tk_como = 30;
  public static final int tk_suma = 44;
  public static final int tk_hora_real = 9;
  public static final int tk_entero = 14;
  public static final int tk_multiplicacion = 46;
  public static final int tk_asignacion_division = 55;
  public static final int tk_fecha_hora_real = 7;
  public static final int tk_decimal_real = 4;
  public static final int tk_curp_real = 11;
  public static final int tk_igualdad = 57;
  public static final int tk_asignacion_multiplicacion = 54;
  public static final int tk_coma = 43;
  public static final int tk_mientras = 36;
  public static final int tk_simbolo = 16;
  public static final int tk_funcion = 27;
  public static final int tk_desigualdad = 58;
  public static final int tk_dos_puntos = 41;
  public static final int tk_menor = 60;
  public static final int tk_funciones = 25;
  public static final int tk_texto_real = 2;
  public static final int tk_codigo_principal = 24;
  public static final int tk_procedimientos = 26;
  public static final int tk_negacion = 65;
  public static final int tk_mayor = 59;
  public static final int tk_rfc_real = 10;
  public static final int tk_y = 63;
  public static final int tk_parentesis_cerrado = 40;
  public static final int tk_entero_real = 3;
  public static final int tk_logico_real = 6;
  public static final int tk_modulo = 48;
  public static final int tk_punto = 42;
}

